trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'backend/pom.xml'
    goals: 'build'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    displayName: 'Build Java Backend'

- task: Npm@1
  inputs:
    command: 'install'
    workingDir: 'frontend'
    displayName: 'Install Angular Dependencies'
